config/routes.rb
Rails.application.routes.draw do
  # Define your application routes per the DSL in https://guides.rubyonrails.org/routing.html

  # Reveal health status on /up that returns 200 if the app boots with no exceptions, otherwise 500.
  # Can be used by load balancers and uptime monitors to verify that the app is live.
  get "up" => "rails/health#show", as: :rails_health_check

  # Defines the root path route ("/")
  # root "posts#index"

  root to: redirect('/home')

  get 'home', to: 'pages#home', as: 'home'
  get 'songs', to: 'pages#songs', as: 'songs'
end

app/models/application_record.rb
class ApplicationRecord < ActiveRecord::Base
  primary_abstract_class
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
end

app/controllers/pages_controller.rb
class PagesController < ApplicationController
  def home
    render :home
  end

  def songs
    render :songs
  end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/pages_helper.rb
module PagesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
  <head>
    <title>BookList</title>
    <meta name="viewport" content="width=device-width,initial-scale=1">
    <%= csrf_meta_tags %>
    <%= csp_meta_tag %>

    <%= stylesheet_link_tag "application", "data-turbo-track": "reload" %>
    <%= javascript_importmap_tags %>
  </head>

  <body>
    <%= yield %>
  </body>
</html>

app/views/pages/home.html.erb
<h1>Book List</h1>

<% time = Time.now %>
<%= time %>

<ul>
  <li><%= image_tag 'hp.jpeg' %> Harry Potter and the Philosopher's Stone by J.K. Rowling</li>
  <li>Harry Potter and the Chamber of Secrets by J.K. Rowling</li>
</ul>

<%= link_to 'Song List', songs_path %>

app/views/pages/songs.html.erb
<h1>Song List</h1>

<ul>
  <li>Work Song by Hosier (Hosier)</li>
  <li>Anything by Sleep Token (Unknown)</li>
</ul>